---
name: NetSDS
version: 1.02
author:
  - 'Net.Style Development Team <info@netstyle.com.ua>'
abstract: Core Perl5 modules for NetSDS VAS development framework
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  CGI: 0
  CGI::Cookie: 0
  CGI::Fast: 0
  Class::Accessor: 0
  Class::Accessor::Class: 0
  Class::ErrorHandler: 0
  Clone: 0
  Config::General: 0
  Data::Structure::Util: 0
  FCGI: 0
  Getopt::Long: 0
  POSIX: 0
  Proc::Daemon: 0
  Proc::PID::File: 0
  Storable: 0
  Unix::Syslog: 0
  perl: 5.008
  version: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  NetSDS:
    file: lib/NetSDS.pm
    version: 1.02
  NetSDS::App:
    file: lib/NetSDS/App.pm
    version: 1.02
  NetSDS::App::FCGI:
    file: lib/NetSDS/App/FCGI.pm
    version: 0.02
  NetSDS::Class::Abstract:
    file: lib/NetSDS/Class/Abstract.pm
    version: 1.01
  NetSDS::Conf:
    file: lib/NetSDS/Conf.pm
    version: 0.02
  NetSDS::Const:
    file: lib/NetSDS/Const.pm
    version: 0.01
  NetSDS::Feature:
    file: lib/NetSDS/Feature.pm
    version: 1.0
  NetSDS::Logger:
    file: lib/NetSDS/Logger.pm
    version: 0.01
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
